
const ApiNames = {
    BASE_URL: 'http://192.168.1.4:4000/',
    GOOGLE_WEB_CLIENT_ID: "1047140993993-gipc4trathfgtcpc371cta3qc21oebe9.apps.googleusercontent.com",
    GOOGLE_IOS_CLIENT_ID: "1047140993993-ckama0mtrvbb6obbht476onedd77rpin.apps.googleusercontent.com",
    GOOGLE_ANDROID_CLIENT_ID: "1047140993993-dnh9aeobaaehovpqm873jsp59j633tgl.apps.googleusercontent.com",
    login: `api/auth/login`,
    validateLoginUser: `api/auth/validateLoginUser`,
    googleLogin: `api/auth/googleLogin`,
    updateKyc: `api/auth/updateKyc`,
    getDocuemtns: `v1/partOrdersBox/getDocuemtns?bookingId=`,
    selectedNotification: `v1/partOrdersBox/selectedNotification?id=`,
    getNotifications: `v1/partOrdersBox/getNotifications`,
    getMessages: `v1/partOrdersBox/getMessages?bookingId=`,
    getNotificationsCount: `v1/partOrdersBox/getNotificationsCount`,
    deleteAllNotifications: `v1/partOrdersBox/deleteAllNotifications`,
    getLocations: `api/users/getLocations`,
    cancelBooking: `api/users/cancelBooking`,
    searchItems: `api/users/searchItems/`,
    getAllSlides: `admin/admin/getAllSlides`,
    getCategory: `admin/admin/getCategory`,
    getAllServices: `admin/admin/getAllServices`,
    wishList: `admin/admin/wishList`,
    getServices: `admin/admin/getServices/`,
    needHelp: `api/auth/needHelp/`,
    getFullProfile: `api/auth/getFullProfile/`,
    getFaq: `admin/admin/getFaq/`,
    getAllDoc: `admin/admin/getAllDoc/`,
    getClient: `api/auth/getClient`,
    getDocByID: `admin/admin/getDocByID/`,
    bookLabTest: `admin/admin/bookLabTest`,
    getDetailsByDoctorId: `api/auth/getDetailsByDoctorId?id=`,
    getFinalCheckout: `admin/admin/getFinalCheckout?info=`,
    getServicesByDoc: `admin/admin/getServicesByDoc?id=`,
    getWsihlistDoct: `admin/admin/getWsihlistDoct?id=`,
    getLabTests: `admin/admin/getLabTests?id=`,
    getWishlist: `admin/admin/getWishlist`,
    getLabTestById: `admin/admin/getLabTestById?id=`,
    getIdByDoc: "api/auth/getIdByDoc?id=",
    getCharges: "api/auth/getCharges?id=",
    BookNow: "api/auth/BookNow",
    getProfile: "api/auth/getProfile",
    getBookings: "api/auth/getBookings",
    updateFMTKeyFirebase: "api/auth/updateFMTKeyFirebase/",
    finalLabTestBooking: "admin/admin/finalLabTestBooking",
}


export default ApiNames;

